### ISSUE TITLE
Could we wake this project ?

### ISSUE THREAD

**Issue by fulup-bzh** [x42/scarlettmixer#1]
While I know you stop your mixer project because of Alsa integration. As ALSA native integration with MIXER does not move forward, I would be please to get a userland mixer to controle my Scarlett 18i8.

I changed USBID to fit with the 18i8 and while your code was not built for the 18i8 when checking ALSA kernel driver https://github.com/smilingthax/alsa-driver_scarlett/blob/s18i8/sound/usb/scarlettmixer.c command looks equivalent.

Note I already ported the ALSA kernel driver that works with 18i8 , but it's a nightmare and you have to redo the job after each kernel update. Outside of this mixer issue the Scarlett board work nicely with JACKd my goal would be to only add a user space mixer to control the board. It would be then easy to write a UI in HTML5 to emulate Windows Mixers.

Conclusion: I would be please to get your code running, to use it as a fundation for a SMALL HTTP/REST server that I could use with an HTML5 UI

When running your code, I got following error. Python find USB board but fail to send to ctrl_send

```
fulup@fulup-tizen:~/Téléchargements/scarlettmixer-master> sudo python scarlettmixer.py 
root's password:
Traceback (most recent call last):
  File "scarlettmixer.py", line 492, in <module>
    sw_impedance(0, impedance.LINEIN)
  File "scarlettmixer.py", line 299, in sw_impedance
    ctrl_send(0x0901 + chn, 0x0100, [mode, 0x00])
  File "scarlettmixer.py", line 43, in ctrl_send
    raise ValueError('request failed')
ValueError: request failed
```

**Comment by x42** [comment]
The main problem here is: while ALSA is using the device, you cannot access it from userspace (device busy).

I found this script handy mainly during reverse-engineering while writing the kernel driver.
Other than that, sure it's GPLv2, re-use it as much as you like.

PS. the smilingthax repo is outdated since everything has already been merged upstream. it's at kernel.org now in vanilla linux and all scarlett devices are supported these days. I think you better write a REST interface around `amixer`.

**Comment by x42** [comment]
oops. didn't mean to close this one.

**Comment by fulup-bzh** [comment]
I would love to use standard Alsa Mixer, but while Scarlett I/O is supported, the Mixer is not working

While searching I got the feeling that Scarlett's Mixer was remove before the integration in main kernel tree. If it is avaliable I would love to know where to find it.

**Comment by x42** [comment]
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/sound/usb/mixer_scarlett.c

It was merged in Nov'2014 and should be in linux 3.19 and later.

**Comment by x42** [comment]
I just verified. Scarlett mixer interface support for 6i6, 18i6, 18i8 and 18i20 is in linux-3.19.1 (current stable) as well as the upcoming 4.0.

What is not supported however is reading out the meters. That part has always been somewhat whacky, since level-meters are not mixer-elements.

**Comment by x42** [comment]
anyway to answer your original question. unload the driver:  eg. `sudo rmmod snd_usb_audio` and the script will work (but then you can't use the device for audio i/o at the same time).

**Comment by fulup-bzh** [comment]
I'm going to try both. Thank you.

**Comment by fulup-bzh** [comment]
Updated to standard OpenSuse Kernel 3.19.1 and everything work out of the box. 

Except if you know a good mixer UI for Scarlett board. My next item on my TDL is to build a mixer UI. While AlsaMixer works, it is not really adapted to control 18inputs.

Thanks again.

**Comment by x42** [comment]
Agreed. The alsa-mixer interface is just basic infrastructure. Having a proper GUI on top would be nice.
https://github.com/trrichard/ScarlettMixer is a project working towards that.

see also https://focusritedevelopmentteam.wordpress.com/2012/04/23/linux-and-focusrite-novation-products/ which is where above project is linked.

**Comment by fulup-bzh** [comment]
Thank you. I'm going to check this. I was thinking about a small REST/AlsaMixer gwateway with an HTML5 on top, but they are many other option.

**Comment by x42** [comment]
sounds good..

If python, then check http://pyalsaaudio.sourceforge.net/libalsaaudio.html#mixer-objects

The ScarlettMixer project is using the  `amixer` commandline tool in "simple" mode . Not the best choice, IMHO. If you must, then I recommend to at least use the "normal" mode:  e.g. `amixer -c 2  contents`, but really accessing it directly is preferable.

**Comment by fulup-bzh** [comment]
I started to look at amixer source code to understand ALSA C API. 
Unfortunately there is no real documentation on mixer API and the entry 
point to build something is higher than it should :(

As today my intention remains to use C API directly. I checked NodeJS 
api native API for ALSA, but nothing serious exists for Alsa mixer. 
Furthermore installing NodeJS ALSA native module is more complex than 
recompiling a small C program. I'm not a Python expert and as I'm aiming 
at building UI in HTML5, using Python would add an extra language to the 
application. Last but not least the existing mixer project does not look 
easy to transform in a REST server.

My intention remains to build a tiny HTTP/REST server using C and talk 
directly to the ALSA API to reproduce as much as possible the native 
Mixer application.

When you say "accessing it directly is preferable" you mean access via 
ALSA API or USB ? I would have preferred a direct access via USB, but I 
got the impression that it imposes to remove USB-audio, wich would 
prevents from using Scarlett with JACK/Ardour in parallel with the MIXER.

Question: in order to have a working solution with Mixer+Ardour+Jack. 
what model would you recommend to develop the Mixer ALSA API or direct 
USB API ?

Thanks for your support.

Fulup

**Comment by x42** [comment]
I meant the alsa-mixer interface:
http://www.alsa-project.org/alsa-doc/alsa-lib/group___mixer.html

Writing it in C is even better, but safely parsing HTTP protocol headers in C is no fun.

**Comment by fulup-bzh** [comment]
I agree with you parsing HTTP is not fun, but Gnu propose a C lib for 
HTTP that should do the job: http://www.gnu.org/software/libmicrohttpd/

**Comment by x42** [comment]
Closing this issue now. it's not an issue anymore.

But this is going to be of wider interest. So please keep us posted, either alsa-user/devel email list or the focusrite devel-blog. Cheers!

**Comment by fulup-bzh** [comment]
I'm sure that I will have few more questions for you. I started to work on an AlsaJsonGateway that expose the equivalent of amixer function on HTTP. As soon as I have something I will post it.

A bientot
